# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: supportdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      # Estas variables alimentan application.yaml
      DB_URL: jdbc:postgresql://db:5432/supportdb
      DB_USER: postgres
      DB_PASSWORD: root

volumes:
  db_data:
