spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://db:5432/supportdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
